### ISSUE TITLE
Library code print

### ISSUE THREAD

**Issue by danielflanigan** [ColumbiaCMB/kid_readout#11]
@gitj Can we agree on making library code not print progress messages by default? It's nice to be able to turn this on for scripts, but it's annoying to have to wade through long messages to find the stack trace of a test that failed. My keyword preference would be quiet=True or verbose=False, or similar.

In particular, it would be nice for the "Writing DRAM bank" and "bank offset..." messages in the roach to not be printed by default.

**Comment by gitj** [comment]
yes, this is a long standing todo. I'll start working on it shortly

**Comment by danielflanigan** [comment]
There are still a few scattered prints but the commonly-encountered ones are either controlled by verbosity or turned into logging calls.
