### ISSUE TITLE
Different nonexistence values in hpd_temps and starcryo_temps

### ISSUE THREAD

**Issue by danielflanigan** [ColumbiaCMB/kid_readout#12]
It looks like hpd_temps uses None to signal that a thermometer doesn't exist, while starcryo_temps uses nan. I'd like to standardize on one (I prefer None) but I don't understand this code or what might be relying on these values. @gitj Thoughts?

**Comment by gitj** [comment]
I prefer nan because when asking for multiple times, an array is returned, and an array of None's will be an object array which is not a good thing here. I went ahead and pushed this change.
