### ISSUE TITLE
strange packet error from roach2 raised IndexError

### ISSUE THREAD

**Issue by danielflanigan** [ColumbiaCMB/kid_readout#13]
@gitj @mabitbol An acquisition script crashed last night with the following error:

```Python
got weird packet (120,)
Wrote /data/detectors/2016-04-27_214555_Tc.nc
Traceback (most recent call last):
  File "apps/data_taking_scripts/tc_measurement.py", line 34, in <module>
    sweep.stream_arrays.append(ri.get_measurement_blocks(num_blocks=1, state=state))
  File "/home/flanigan/kid_readout/kid_readout/roach/interface.py", line 606, in get_measurement_blocks
    data, seqnos = self.get_data(num_blocks,demod=demod)
  File "/home/flanigan/kid_readout/kid_readout/roach/heterodyne.py", line 365, in get_data
    return self.get_data_udp(nread=nread, demod=demod)
  File "/home/flanigan/kid_readout/kid_readout/roach/r2heterodyne.py", line 108, in get_data_udp
    addr=(self.host_ip, 55555))  # , stream_reg, addr)
  File "/home/flanigan/kid_readout/kid_readout/roach/r2_udp_catcher.py", line 38, in get_udp_data
    darray,seqnos = decode_packets(pkts,nchans)
  File "/home/flanigan/kid_readout/kid_readout/roach/r2_udp_catcher.py", line 57, in decode_packets
    data = np.hstack(raw_data)
  File "/home/flanigan/miniconda2/envs/kid_readout/lib/python2.7/site-packages/numpy/core/shape_base.py", line 277, in hstack
    if arrs[0].ndim == 1:
IndexError: list index out of range
```

I can wrap my code to continue on exceptions like this, but it would be nice to have bad packets just produce NaN data without raising an exception.

**Comment by mabitbol** [comment]
I’ll fix this with nans.

**Comment by danielflanigan** [comment]
Thanks, Max. Feel free to close this when the changes are pushed.

**Comment by mabitbol** [comment]
Bad and missing packet data is now replaced with NaNs.  Bad/missing packet statistics are returned by decode_packets but this has not be propagated up yet.

**Comment by danielflanigan** [comment]
Just got another IndexError:
```python
Traceback (most recent call last):
  File "apps/data_taking_scripts/lo_scan_r2.py", line 74, in <module>
    sweep.stream_arrays.append(ri.get_measurement_blocks(num_blocks=1, state=state))
  File "/home/flanigan/kid_readout/kid_readout/roach/interface.py", line 603, in get_measurement_blocks
    data, seqnos = self.get_data(num_blocks,demod=demod)
  File "/home/flanigan/kid_readout/kid_readout/roach/heterodyne.py", line 365, in get_data
    return self.get_data_udp(nread=nread, demod=demod)
  File "/home/flanigan/kid_readout/kid_readout/roach/r2heterodyne.py", line 108, in get_data_udp
    addr=(self.host_ip, 55555))  # , stream_reg, addr)
  File "/home/flanigan/kid_readout/kid_readout/roach/r2_udp_catcher.py", line 38, in get_udp_data
    darray, seqnos, num_bad_pkts, num_dropped_pkts = decode_packets(pkts,nchans)
  File "/home/flanigan/kid_readout/kid_readout/roach/r2_udp_catcher.py", line 51, in decode_packets
    start = np.fromstring(plist[0],'<u4')[-1]
IndexError: list index out of range
```

**Comment by mabitbol** [comment]
Ok I think this happens when all the packets are bad.    It looks like you are trying to get only 1 packet, I think you should get more than 1 in case of a bad packet.  I have fixed it now by returning an empty array

**Comment by gitj** [comment]
I think we should ensure that you always get at least one packet. But we
should also note that for 256 channels, 1 packet means one sample per
channel so getting one packet is probably rarely something we would
actually want except when reading out very few channels.
On May 5, 2016 7:44 AM, "Max Abitbol" <notifications@github.com> wrote:

Ok I think this happens when all the packets are bad. It looks like you are
trying to get only 1 packet, I think you should get more than 1 in case of
a bad packet. I have fixed it now by returning an empty array

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/ColumbiaCMB/kid_readout/issues/13#issuecomment-217173047>

**Comment by mabitbol** [comment]
Ok instead we return nans if all the packets are bad

**Comment by danielflanigan** [comment]
That sounds good. To minimize surprise, I think the function should be
called what it does: if it returns the data from a fixed number of packets
it should be get_data_packets, and similarly for fixed numbers of samples
per channel or n-sample blocks per channel. Thoughts?

Agree that the length of the return array should be completely specified by
the call, but the content can be nans if there's missing data.

**Comment by gitj** [comment]
Right now the idea is that get_measurement uses blocks_per_second to figure
out how many blocks to request from get_measurement_blocks. Even though a
"block" for this mode is a packet, it is still logically a block. The
definition of a block of data that I've been using (though it's not
documented) is the smallest unit of information that can be transferred
from the ROACH. For the ROACH 1 code that was truly a "block" while for
ROACH 2 it is a packet.

So my preference is to leave the naming the same and to emphasize that
get_measurement_blocks is an expert function.

**Comment by mabitbol** [comment]
Ok, this should be fixed as we discussed.  The get data function now returns exactly the number of packets that it was called with.
