### ISSUE TITLE
Some heterodyne sweep data is missing one sample

### ISSUE THREAD

**Issue by danielflanigan** [ColumbiaCMB/kid_readout#14]
@gitj @mabitbol I took some data with the roach2 on the Nb CPW chip downstairs. Specifically, I ran `apps/data_taking_scripts/heterodyne_scan_measurement_roach2.py` with no modifications. While taking the data I saw a fair number of `got strange packet` and `got bad packet` errors that didn't raise exceptions.

The issue is that the length of the raw data in each chunk (StreamArray.s21_raw) varies between 8192 and 8191 samples. Maybe 5-10% of the data is missing one sample, and there's no pattern I can see. Since this data is coming straight out of the roach, it looks like an off-by-one error in some packet catching code or something. Maybe this will also be fixed by #13?

Missing one sample isn't a tragedy, but this is irritating because it breaks some code that expects these arrays to all have the same shape.

@gitj did you have this same problem when you ran this script?

**Comment by mabitbol** [comment]
This should be fixed by the NaN replacement
