### ISSUE TITLE
move docstring

### ISSUE THREAD

**Issue by gitj** [ColumbiaCMB/kid_readout#21]
https://github.com/ColumbiaCMB/kid_readout/blob/master/kid_readout/measurement/basic.py#L318
https://github.com/ColumbiaCMB/kid_readout/blob/master/kid_readout/measurement/basic.py#L460
https://github.com/ColumbiaCMB/kid_readout/blob/master/kid_readout/measurement/basic.py#L723
https://github.com/ColumbiaCMB/kid_readout/blob/master/kid_readout/measurement/basic.py#L1111

@danielflanigan having the detailed docstring on `__getitem__` is less helpful because you have to artificially type `measurement.__getitem__` to see it in ipython/jupyter. The place you want to see the docstring is when you have typed i.e. `measurement.sweep()`

**Comment by danielflanigan** [comment]
Fixed by e4e34522012e3f5d2b657f0213c2490c3d68915f
